export const dummyUsers = [
  {
    firstName: "Elon",
    lastName: "Musk",
    emailId: "elon@gmail.com",
    password: "Elon@1234",
    gender: "Male",
    age: 52,
    about: "Entrepreneur, engineer, and innovator behind SpaceX and Tesla.",
    photoUrl: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    firstName: "Taylor",
    lastName: "Swift",
    emailId: "taylor@gmail.com",
    password: "Taylor@1234",
    gender: "Female",
    age: 34,
    about: "Singer-songwriter, storyteller, and performer.",
    photoUrl: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    firstName: "Virat",
    lastName: "Kohli",
    emailId: "virat@gmail.com",
    password: "Virat@1234",
    gender: "Male",
    age: 35,
    about: "Indian cricketer and fitness enthusiast.",
    photoUrl: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    firstName: "Emma",
    lastName: "Watson",
    emailId: "emma@gmail.com",
    password: "Emma@1234",
    gender: "Female",
    age: 33,
    about: "Actress, activist, and advocate for gender equality.",
    photoUrl: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    firstName: "Cristiano",
    lastName: "Ronaldo",
    emailId: "cristiano@gmail.com",
    password: "Cristiano@1234",
    gender: "Male",
    age: 39,
    about: "Footballer with passion and dedication.",
    photoUrl: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    firstName: "Selena",
    lastName: "Gomez",
    emailId: "selena@gmail.com",
    password: "Selena@1234",
    gender: "Female",
    age: 32,
    about: "Singer, actress, and producer.",
    photoUrl: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    firstName: "ShahRukh",
    lastName: "Khan",
    emailId: "shahrukh@gmail.com",
    password: "Shahrukh@1234",
    gender: "Male",
    age: 58,
    about: "Bollywood actor known as King Khan.",
    photoUrl: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    firstName: "Priyanka",
    lastName: "Chopra",
    emailId: "priyanka@gmail.com",
    password: "Priyanka@1234",
    gender: "Female",
    age: 41,
    about: "Actress, producer, and global icon.",
    photoUrl: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    firstName: "Lionel",
    lastName: "Messi",
    emailId: "lionel@gmail.com",
    password: "Lionel@1234",
    gender: "Male",
    age: 37,
    about: "Footballer and legend in the game.",
    photoUrl: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    firstName: "Zendaya",
    lastName: "Coleman",
    emailId: "zendaya@gmail.com",
    password: "Zendaya@1234",
    gender: "Female",
    age: 28,
    about: "Actress and style icon.",
    photoUrl: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    firstName: "Narendra",
    lastName: "Modi",
    emailId: "narendra@gmail.com",
    password: "Narendra@1234",
    gender: "Male",
    age: 74,
    about: "Prime Minister of India.",
    photoUrl: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    firstName: "Bill",
    lastName: "Gates",
    emailId: "bill@gmail.com",
    password: "Bill@1234",
    gender: "Male",
    age: 68,
    about: "Philanthropist and co-founder of Microsoft.",
    photoUrl: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    firstName: "Deepika",
    lastName: "Padukone",
    emailId: "deepika@gmail.com",
    password: "Deepika@1234",
    gender: "Female",
    age: 38,
    about: "Bollywood actress and producer.",
    photoUrl: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    firstName: "Barack",
    lastName: "Obama",
    emailId: "barack@gmail.com",
    password: "Barack@1234",
    gender: "Male",
    age: 63,
    about: "Former President of the United States.",
    photoUrl: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    firstName: "Ariana",
    lastName: "Grande",
    emailId: "ariana@gmail.com",
    password: "Ariana@1234",
    gender: "Female",
    age: 31,
    about: "Singer and performer.",
    photoUrl: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    firstName: "Ratan",
    lastName: "Tata",
    emailId: "ratan@gmail.com",
    password: "Ratan@1234",
    gender: "Male",
    age: 87,
    about: "Business magnate and philanthropist.",
    photoUrl: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    firstName: "Anushka",
    lastName: "Sharma",
    emailId: "anushka@gmail.com",
    password: "Anushka@1234",
    gender: "Female",
    age: 36,
    about: "Actress and producer.",
    photoUrl: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    firstName: "Tom",
    lastName: "Holland",
    emailId: "tom@gmail.com",
    password: "Tom@1234",
    gender: "Male",
    age: 28,
    about: "Actor, known for playing Spider-Man.",
    photoUrl: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    firstName: "Kylie",
    lastName: "Jenner",
    emailId: "kylie@gmail.com",
    password: "Kylie@1234",
    gender: "Female",
    age: 27,
    about: "Entrepreneur and media personality.",
    photoUrl: "https://randomuser.me/api/portraits/women/19.jpg",
  },
 
];
